### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by Sean0719** [zer0uno/K-Shortest-Paths#1]
Hi,

Recently, i run this code but there is an error: Programma lanciato con parametri sbagliati: ./my_prog test_file. So how can i solve this error. Thanks.

**Comment by zer0uno** [comment]
@Sean0719 Hi, when launching the script you have to provide a file containing the paths. You could use one of those present in the `test/` directory in this way: `main.py test/test_10`

**Comment by Sean0719** [comment]
Thank you very much.
