### ISSUE TITLE
test file format

### ISSUE THREAD

**Issue by Sean0719** [zer0uno/K-Shortest-Paths#2]
Hi,

One more question, i want to use my own dataset. So what is test_10 file's type? Such as .text .csv? Thank you very much.

**Comment by zer0uno** [comment]
Hi @Sean0719, the file must be a .text one, where the first line states the number of nodes and th following lines each declares a path and its cost, for example `1 2 7` states that there is a path going from node 1 to node 2 and costs 7.

**Comment by Sean0719** [comment]
Okay, i got it. Thanks again for your kind help.

**Comment by zer0uno** [comment]
No, prob. If you have other questions don't hesitate.
