### ISSUE TITLE
Wrong Data type?

### ISSUE THREAD

**Issue by Sean0719** [zer0uno/K-Shortest-Paths#3]
Hi,

Sorry to disturb you again. According to your suggestion, i create my own dataset and try several times, but finally i still get the following error:
""""""""""""""""""
KShort>python main.py test/test_6801.text
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    main()
  File "main.py", line 12, in main
    graph, num_nodes, num_arcs, graph_imm_path = tools.getGraphStructure(sys.argv[1])        
  File "F:\AAU_20181101\KShort\tools.py", line 70, in getGraphStructure
    graph_matrix[head][tail] = cost
IndexError: list assignment index out of range
"""""""""""""""""""""""""""""""""""""""""""""""""""""
I also try to generate a simple test file by myself, which i also failed. To this points, it seems that my the error comes from my datasetfile test_6081.text. So, I upload my dataset file on the googledrive( https://drive.google.com/open?id=1_Lcv3phEuEmcNLDd36jhgLyC8kCdthpD ), could you please help me to find that where i am wrong? In addition, you can see my code for getting the text file as follows:
*********************************
with open('test_6081.txt', 'w') as netf:
    netf.write(str(len(newList)))
    netf.write('\n')
    netf.write('\n')
    for i, j,t in zip(list1, list2, list33): 
        str1 = str(i) + ' ' + str(j) + ' ' + str(t)
        netf.write(str1)
        netf.write('\n')
netf.close()
***********************************************
 Thank you very much.

**Comment by zer0uno** [comment]
Hi, try to correct your dataset. I see that there should be 6800 nodes but there are node numbers that are greater than 6800 value. If the nodes are 6800 there should be nodes from 1 to 6800.

**Comment by Sean0719** [comment]
Hi,
I can run it now.  Thanks for your kind help.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zeroUno <notifications@github.com>
发送时间: Sunday, December 30, 2018 10:33:57 AM
收件人: zer0uno/K-Shortest-Paths
抄送: Sean0719; Author
主题: Re: [zer0uno/K-Shortest-Paths] Wrong Data type? (#3)


Hi, try to correct your dataset. I see that there should be 6800 nodes but there are more numbers that are greater than 6800 value. If the nodes are 6800 there should be nodes from 1 to 6800.

―
